GEUS-Glaciology-and-Climate/pypromice

src/pypromice/L0toL1.py, src/pypromice/aws.py, src/pypromice/test/test_config1.toml, src/pypromice/test/test_config2.toml, src/pypromice/variables.csv
This addresses #68 and also comprehensively addresses the application of time shifting for any situation of file format and logger type. See the docstrings in `_addTimeShift` for further details.
I am not super familiar with going back and forth between xarray and pandas. You will see that I chose to do the work in `_addTimeShift` using pandas. Please double check my methods of returning back to xarray and re-assigning the attributes. It is pretty simple, but just not something I have done in the past.
Also, a general check of the logic depending on file format and logger type would be good. I embedded in the code with both tx v2 and tx v3 sample stations to confirm the use of `concat` and to confirm that the time-shifting is performing as intended.
=> Modify time shift

src/pypromice/aws.py
L3 filenames should now be correctly assigned names in the following format: `<station-name>_<time-resolution>.<file-type>`. Where the time resolution is defined from the `aws.L3` object.
=> L3 file name de-bug, #70

bin/getBUFR, src/pypromice/postprocess/csv2bufr.py
This uses already built-in building of positions dict to write a csv file to the `aws-l3` repo.
The positions are the most recent point on 3 month linear regression trends. There is some inconsistency, in that we only look for and use modem positions when GPS positions are missing for stations that make it through to BUFR submission. There are many scenarios in `getBUFR` where a station is skipped or rejected for BUFR processing. I have captured all of these situations and we will still write position metadata to the csv file for these stations (but only using GPS, not modem).
EDIT: The above was fixed! See following commits and comments.
This will require to run as `getBUFR --positions` in processing script.
=> implement writing of position csv file to aws-l3

bin/getL0tx, src/pypromice/tx.py
Modification to `getL0tx` will write the previous `last_uid` back to the ini file if no new messages are found.
The modification to `tx.py` is simply to improve the print statement. The `last_uid` should not be included in the list of new UIDs that is printed. As commented in the code, the search command always returns at least the most recent message, even if it has already been processed. So just remove from the print (it is also skipped in the processing).
Resolves: #76
=> persist uid in ini file

src/pypromice/postprocess/wmo_config.py
Instantaneous pressure recently went bad on these stations. Pressure is a key variable for DMI/WMO. Need to skip these stations for now.
=> skip NAU and CP1

bin/getBUFR, src/pypromice/postprocess/csv2bufr.py, src/pypromice/postprocess/wmo_config.py
This PR has two updates:
1. Modify the `fetch_old_positions` function. This is used to grab positions for stations that were otherwise skipped or rejected from BUFR processing, so that we can still write their positions to the csv file (if available). A bug in the previous version of this was preventing some stations from flowing through the function.
2. Implement a method to skip specific variables for specific stations, using the config file. This was prompted by bad values for `p_i` that were identified by DMI for `CP1` and `NAU`.
As noted in the code, we need to be aware that if air temperature or pressure are not reporting at all (value is `NaN`), then the station is skipped entirely, as per `min_data_check()`. This new config setting therefore only applies to stations that are …
=> WMO positions & variable skipping

bin/getMsg, setup.py, src/pypromice/tx.py
`bin/getMsg` function added for grabbing and saving transmission messages. It is intended for this to work alongside the current operational processing to back-up transmission messages in a local file space (rather than relying on remote Gmail storage).
I also replaced a line in `tx.getMail` to only print a statement of the newest message `uid` rather than printing them all - it can get pretty lengthy otherwise.
=> Message grabber added

src/pypromice/postprocess/csv2bufr.py
We process `CEN2` file, but lookup the stid for BUFR submission using `CEN` as the registered station name.
=> rename CEN2 to CEN

src/pypromice/L2toL3.py, src/pypromice/aws.py
There was an unneeded resampling step included in `L2toL3` that meant all outputs were hourly resolution (including `L3 raw`, which should be `10min`). This was probably leftover from the IDL/GDL processing translation to Python. 
This step has been removed, only using the resampling step in the `aws` object.
Sorry for using an odd branch to pull request this from, but given the data fixing is already being developed from the `fixing-data` branch, this branch was redundant.
=> Resampling step in L2toL3 removed

setup.py
Because we are releasing a new Dataverse AWS dataset, I think the pypromice version needs to move up also (as we will also publish pypromice to Dataverse again). 
I explained in #79 that keeping consistent version naming conventions between Github, pip and Dataverse is tricky.
>At the moment, our [pypromice releases](https://github.com/GEUS-Glaciology-and-Climate/pypromice/releases) on GitHub are mismatched with our Dataverse versioning (found here: [https://doi.org/10.22008/FK2/IPOHT5](https://doi.org/10.22008/FK2/IPOHT5)). This is because Dataverse versioning is fixed to single digit naming conventions `V1, V2, V3...`. For example, the most recent pypromice release on GitHub is `v0.0.1`, however on Dataverse the same release is called `V1`. **This presents ambiguity.**
>**I propose that …
=> Version change

bin/getL0tx, bin/getMsg, bin/getWatsontx
Quick PR to address the following deprecation warning:
```
DeprecationWarning: This method will be removed in future versions.  Use 'parser.read_file()' instead.
accounts_ini.readfp(open(accounts_file))
```
Also corrected my previous bad comment re: indentation since I had the file open!
=> Deprecated readfp

.github/workflows/url_update.yml, bin/updateURL
This update is to automatically update the `data_url.csv` look-up table used in `pypromice.get`. By doing so, we can overcome the problem of out-of-date data file DOIs in the AWS Dataverse entries (as outlined in #94). 
Two files are added:
- `bin/updateURL`: To perform the URL update to `data_urls.csv`
- `/github/workflows/url_update.yml`: To perform the Github Action. This uses a Dataverse Token and Github Token for accessing the Dataverse API and pushing any changes to `data_urls.csv` back to the repo `main` branch 
Currently the Github Action is scheduled for 12pm on the first day of each month, which should coincide with future scheduled Dataverse releases. It can also be manually triggered.
=> Automated data_url.csv updater in Github Action

bin/getData, src/pypromice/aws.py, src/pypromice/get.py
As the `AWS` object processing is now only performed with `AWS.process()` and not on initialisation, we no longer need a `self.outpath` object variable. This is just defined when a user calls `AWS.write(<outpath>)`. This just had not been updated in `aws.py`. Without this, the writing of the output files will not work as it is looking for an outpath object variable that does not exist.
=> self.outpath removed from AWS object

.github/workflows/process_test.yml, setup.py
`.github/process_test.yml ` performs pypromice processing tests on real AWS data from PROMICE and GC-Net stations. This is triggered on pull requests to the `main` branch of `pypromice` as a Github Action, and can also be manually triggered. Similar to` .github/unit_test.yml` #101, a pull request can not be accepted until this workflow successfully passes. In addition, output files are posted as a Github Action artifact after each run [here](https://github.com/GEUS-Glaciology-and-Climate/pypromice/actions/workflows/process_test.yml), so they can be viewed and checked.
A few notes:
- This action only performs processing in a Python 3.8 environment (which is what we are currently using in our operational processing). We could run it on other Python versions too, if necessary
- I came across …
=> Process testing triggered on PR

src/pypromice/process/aws.py
This addresses comments from Øystein at Norwegian Met Service, that long int (int64) dtype is incompatible with OPeNDAP access on the THREDDS server.
Are there any concerns that this will break anything else using the .nc files?
The [year 2038 problem](https://en.wikipedia.org/wiki/Year_2038_problem) appears to be a real concern, but I suppose we don't worry about that now! (And hopefully down the road THREDDS and/or OPeNDAP will upgrade to support this).
=> encode with i4 dtype

docs/guide_user.rst, docs/install.rst, src/pypromice/process/aws.py
In response to #135 and #136, these changes address the following:
- A unit testing guide has now been added to test the pypromice installation. This is in the [installation section of the readthedocs](https://pypromice.readthedocs.io/en/docs-plt-test/install.html#developer-install)
- Simple plotting examples have been aded to the [user guide section of the readthedocs](https://pypromice.readthedocs.io/en/docs-plt-test/guide_user.html#plotting-our-data). These straightforward examples use the plotting functionality of xarray and pandas 
These can be viewed on the readthedocs flavour of this repo branch [here](https://pypromice.readthedocs.io/en/docs-plt-test/).
=> Documentation for unit testing and plotting

src/pypromice/process/L0toL1.py
Only z_boom_u and (if present) z_boom_l were corrected for the effect of air temperature.
z_stake should also be corrected for that.
It will require a full reprocessing of the catalogue and an update on the dataverse.
=> Corrected missing air temp correction for z_stake

docs/conf.py, docs/guide_user.rst, docs/index.rst, docs/install.rst, docs/requirements.txt
These modifications address #138 and the following comments from @simonrp84. The changes can also be seen [here](https://pypromice.readthedocs.io/en/joss-doc-edits/index.html) on pypromice's readthedocs
> I think the index page for readthedocs could be improved. Can you add an additional sentence or two after "pypromice is designed for processing and handling PROMICE automated weather station (AWS) data." to describe what PROMICE data is and why a tool is needed to handle it? I know you mention this elsewhere, but it would be nice tohave that up-front in the docs.
Description added to index page.
> It's not immediately clear in the readthedocs pages where the example .toml files are located, it owuld be good to directly specify where the example toml files are from within the user guide …
=> Index, installation and guides docs modified

bin/getBUFR, src/pypromice/postprocess/csv2bufr.py, src/pypromice/postprocess/wmo_config.py
Fixing [this issue](https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/issues/46)
> **The problem:**
> 
> When GetBUFR was being called, a linear fit based on the last three months of lat, lon and alt was calculated. For latitude and longitude, coordinates contained in the Iridium emails were used to gap-fill missing observation of latitude and longitude, meaning that there was always data to fit a linear function on. For altitude, however, a failing GPS over more than 3 months would  lead to the absence of observed altitude to build a linear function. In those cases, altitude is left as NaN in the BUFR file sent to DMI/WMO and saved in [AWS_station_locations.csv](https://geusgitlab.geus.dk/glaciology-and-climate/promice/aws-l3/-/blob/main/AWS_station_locations.csv).
> …
=> extrapolate gps_alt from entire record if needed

.github/workflows/pypi-publish.yml, .github/workflows/python-publish.yml, README.md, docs/index.rst, docs/install.rst, setup.py
This PR is for pypi building of the `pypromice` package, including:
- Updated documentation
- A Github Action which should build and publish pypi package automatically when a new release of `pypromice` is made from this repo
I have also begun exploring pypromice distribution as a `conda-forge` package, however, this requires some coordination with `pydataverse`, one of our dependencies. See open issue [here](https://github.com/gdcc/pyDataverse/issues/159) for more details.
=> pypi build for JOSS review

src/pypromice/get.py
This is a patch to update the DOIs in the `pypromice.get` module, removing the old two-boom AWS DOI.
=> two-boom DOI removed

bin/getL0tx, src/pypromice/get.py, src/pypromice/process/aws.py, src/pypromice/process/variables.csv
t_rad and t_string were set to instant obs in the metadata,
and were not timeshifted an hour back in pypromice.
But they are an hourly average and are now set to False in the instantenous_hourly column in the variables.csv file, so now they are timeshifted.
=> Setting instantenous_hourly to False at t_rad and t_string 

src/pypromice/postprocess/csv2bufr.py
Quick fix removing the gap-filling of missing GPS data with coordinates from the Iridium emails.
Those bad coordinates are causing the issues reported in #152. 
I am suspecting that some stations' position are heavily relying on the (bad) coordinates from the Iridium messages. This update will probably mean that those stations will not have coordinates in AWS_latest_locations.csv anymore. But this should be fixed (later) by linear fits of lat, lon and altitude from the entire record. This also means that it needs to be done elsewhere than in the function "getBUFR" which currently only looks at transmission.
=> Removing coordinate gap-filling using Iridium SBD coordinates

src/pypromice/process/L0toL1.py, src/pypromice/process/L1toL2.py, src/pypromice/process/L2toL3.py, src/pypromice/process/aws.py, src/pypromice/process/variables.csv
Many improvements. 
The main one being:
- the removal of unnecessary variables and filters on bedrock stations
Note that [added a "skip_processing" key word in "comment" column of "variable.csv"](https://github.com/GEUS-Glaciology-and-Climate/pypromice/pull/172/commits/041b033fd27782732d3e2e4af799aa64f5e91868) was a first idea of a variable-specific processing switch, but it was reverted and the "bedrock" attribute defined in the config files (False if not defined) is used instead to decide if some variables shoud be skipped.
- harmonizing variables in the csv and netcdf
- moving the directional wind speed and making its calculation fail-safe (described in commit)
- some small changes to stop log(0) warnings or pd.read_csv date_parser deprecation warnings or to make assert errors more …
=> Fixing tundra processing variable writing and wrong negative longitudes

src/pypromice/process/aws.py, src/pypromice/process/variables.csv
- The attribute "bedrock" was saved as a string and not as a boolean. As a result cloud cover and THF were not written into files.
- Removing gps_numsat, gps_q, batt_v_ini, batt_v_ss, freq_vw from L3 product.
Tested on glacio01.
Needed before the next dataverse release.
=> Fixing typo in aws write and removing unused variables

src/pypromice/postprocess/wmo_config.py
In response to Robert's email:
```
We made some updates to the PROMICE AWSs:
QAS_M decommissioned, replaced by QAS_Mv3
QAS_U decommissioned, but we have QAS_Uv3
NUK_U decommissioned, but we have NUK_Uv3
There is a new KAN_Lv3
```
All four of these stations should be in `stid_to_skip['use_v3']`.
For review, any station listed in `stid_to_skip` will be skipped in `getBUFR`. However, if we are processing a v3 station (e.g. `NUK_Uv3`) and the "base" station name (e.g. `NUK_U`) is listed in `stid_to_skip['use_v3']` then we will process the v3 station and strip the `v3` from the name so we are submitting to WMO with the registered non-v3 name.
The `discontinued` list is used for stations that have been discontinued and do not have a v3 and non-v3 version.
If @ladsmund will be maintaining the …
=> Update use_v3 list in wmo_config.py

src/pypromice/postprocess/wmo_config.py
* QAS_Lv3 is no longer a test station
=> Removed QAS_Lv3 from v3_bad and added to use_v3

CITATION.cff, README.md, docs/index.rst
As pointed out by @mankoff in #187, citation prompts on repos are a handy and simple thing to implement.
The authorship follows the Dataverse entry for the most recent pypromice release, `v1.3.0`, which is also updated here in the repo readme and readthedocs page.
=> CITATION.cff file added

src/pypromice/postprocess/wmo_config.py
KPC_L and KPC_U are not working correctly according to @robertfausto .
=> Moved KPC_L and KPC_U to v3_bad

.github/workflows/process_test.yml, .github/workflows/unit_test.yml
This was raised by @BaptisteVandecrux in his latest PR #207 where the unit test was not working due to the `pkg_resources` package not being recognised.
I discovered the problem was with the Github Action itself - we are using an old version of the `checkout` and `setup-python` Actions, which have just been deprecated. So I have updated these in this PR. 
In addition, to make sure we don't have problems from this again, I have hard coded for the `setuptools` package to be upgraded during the Python setup step in each Action. This should mean that the `pkg_resources` package will be found for running the unit test and process test.
After this PR is merged with the main branch, then you should be able to run the Actions on your PR @BaptisteVandecrux. Then you should be able to continue with …
=> Action unit test and process test versions updated

src/pypromice/process/L1toL2.py, src/pypromice/process/variables.csv
- https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/issues/75
- adjusted max ice/firn temperature to 1 degC:  if it is positive, then it's either dysfunctional or exposed to sunlight. Then it is not working as intended. Periods of bad negative values linked with malfunctions or surfacings will need to be filtered manually.
=> Fixing t_surf filtering and adjusting ice/firn temperature upper threshold

src/pypromice/qc/github_data_issues.py
While trying to prescribe an open-ended adjustments, I noticed that it currently causes an error.
When we read the start end end times of adjustments, they receive a time zone info due to their ISO format. The AWS xarray dataset does not have a time zone info (because of an [xarray limitation](https://github.com/pydata/xarray/issues/3291)). So the timezone info is removed from the adjustments time bounds (l.183-184).
What was missing is that when start or end date of adjustments are blank (meaning open-start, open-ended bounds), we use a timestamp (then time-zone-naive) from the AWS dataset, and that it then causes an error later on when trying to remove the time-zone info from these same time-zone-naive bounds.
=> fixing open-ended adjustements error

src/pypromice/postprocess/csv2bufr.py
* z_boom_u was incorrectly used to calculate heightOfBarometerAboveMeanSeaLevel.
* Added offset parameter for defining barometer height relative to gps 
Addressing issue: #218
=> Fixed issue where heightOfBarometerAboveMeanSeaLevel was depending on z_boom_u 

docs/requirements.txt
This is a simple patch to the readthedocs searching abilities at https://pypromice.readthedocs.io. 
[There has been a security vulnerability](https://github.com/readthedocs/readthedocs-sphinx-search/security/advisories/GHSA-xgfm-fjx6-62mj) found in a previous version on readthedocs-sphinx-search, so the simple solution is to just update the version.
I've tested the readthedocs build with the new version, and it all works fine.
=> Readthedocs sphinx-search version updated

.github/workflows/unit_test.yml, src/pypromice/process/L0toL1.py
The unit test was beginning to fail. It is probably caused by an implicit upgrade to pandas or another dependency.
=> Ci unittest fix

src/pypromice/process/value_clipping.py, src/pypromice/process/variables.csv, src/pypromice/qc/github_data_issues.py
changes from #224 re-applied from the latest main branch
- found a bug in the way rh_u and rh_l were clipped (#220 )
- adjusted upper limit of rh to 100% which is the instrument specification when RH is with regards to water (rh_cor, with regards to ice can be >100 and has an upper limit of 150 a.t.m.)
- msg_lat and msg_lon are not precise enough and linear regression (even noise-resilient ones like RANSAC) were shown to fail at different places (#152). So they are removed from the output. They are still scraped from the emails by the tx-handling scripts (which I am not familiar with and didn't want to mess up with)
=>  Bug fix for RH limits, removed unecessary download of flag/adjustment files, removing msg_lat msg_lon from output

src/pypromice/process/L1toL2.py
Addressing  [#232 rh_cor should not be computed if temperature is not available](https://github.com/GEUS-Glaciology-and-Climate/pypromice/issues/232)
=> Removing rh_cor values when T is missing

src/pypromice/process/L1toL2.py, src/pypromice/process/L2toL3.py, src/pypromice/process/aws.py, src/pypromice/process/variables.csv, src/pypromice/qc/percentiles/thresholds.csv, src/pypromice/qc/persistence.py
https://github.com/GEUS-Glaciology-and-Climate/pypromice/blob/304a2706954fb7b2521901807477a3f33e94656e/src/pypromice/process/L1toL2.py#L69-L73
https://github.com/GEUS-Glaciology-and-Climate/pypromice/blob/304a2706954fb7b2521901807477a3f33e94656e/src/pypromice/qc/persistence.py#L23-L24
Done through
- a persistence QC on gps_lat, gps_lon
- a persistence QC on gps_alt
https://github.com/GEUS-Glaciology-and-Climate/pypromice/blob/304a2706954fb7b2521901807477a3f33e94656e/src/pypromice/qc/persistence.py#L20-L21
If variable 'gps_lat_lon' is given then only times when *both* gps_lat and gps_lon are static are being removed
https://github.com/GEUS-Glaciology-and-Climate/pypromice/blob/304a2706954fb7b2521901807477a3f33e94656e/src/pypromice/qc/persistence.py#L79-L100
- removing all the elevations …
=> QC on GPS data + removing dlr/ulr for bad t_rad + recalculating RH from averaged vapour pressures

src/pypromice/tx/payload_formats.csv
New GC-Net tx message decoding format added to `src/pypromice/tx/variables.csv`
Message type: 95	
Expected message length: 46	
Message format: tfffffffffffffffffffffffffffffffgnefffffffffff	
Description: THE GC-NET VERSION!
=> New GC-Net tx message format added

tests/e2e/test_process.py
I've changed the naming conventions for the unit tests in e2e, as we have talked about, to update all function names consistently.
=> Naming conventions changed

tests/e2e/test_process.py
Added missing "test" prefix required by the unittest framework.
=> Renamed e2e unittest methods

src/pypromice/postprocess/bufr_to_csv.py, src/pypromice/process/aws.py, src/pypromice/utilities/git.py, tests/e2e/test_get_l2.py
* Now includes the git commit ID in the source string when the repository has uncommitted changes for reference.
* Removed assumptions about relative paths and repository roots in the input file paths. The previous approach assumed the data issues path was already the root, causing the function to fail.
=> Updated the `attrs['source']` hash strings:

setup.py
Minimum Python version updated from 3.8 to 3.10. This is because >3.10 is faster and better suited for our installation tests.
=> Minimum Python version updated

src/pypromice/resources/file_attributes.csv
This pull request includes the following changes:
- Updated `geospatial_vertical_units` in `file_attributes.csv` to "meters".
- Corrected typos in field names (`creater_email` → `creator_email`, `creater_url` → `creator_url`) in `file_attributes.csv`.
- Updated the `cdm_data_type` field in `file_attributes.csv` to "Station"
The cdm_data_type attribute describes the fundamental organization of the data within the file according to the Climate and Forecast (CF) / Attribute Convention for Dataset Discovery (ACDD). It helps clients and tools understand whether the data represent a grid, trajectory, time series, station, swath, etc.
=> Update `file_attributes.csv` values and fix typos

src/pypromice/core/variables/station_boom_height.py, src/pypromice/pipeline/L0toL1.py, tests/variables/test_station_boom_height.py
Includes:
- adjust function to correct SR50 measurements for air temperature
- a new proposed adjust function from #350 where uncorrected SR50 measurements are used where air temperature is not provided (e.g. during big data gaps)
Currently the original adjust function is implemented in the pipeline. However, it would be an easy switch to implement the new proposed adjust function.
=> pypromice.core.variables.station_boom_height submodule added

src/pypromice/core/qc/value_clipping.py, src/pypromice/resources/variables.csv, tests/unit/test_value_clippping.py
First of all, OOL originally stood for "out of limit". I don't know how it eventually got used to map variable dependencies.
For many variables we were:
1) correcting (e.g. `z_pt` with `p_u` creating `z_pt_cor`)
2) filtering (e.g. on bad `p_u`)
3) failed to set the dependency between an input variable (`p_u`) and a corrected/dependent variable (e.g. `z_pt_cor`)
Note that only strict dependencies should be informed there (where NaN in input should be NaN in derived variable).
For variables like `z_surf_combined` `snow_height` `d_t_i_*` interpolations within the derivation can lead to non-NaN values when inputs have NaNs. 
New behavior:
Old behavior would be that the outliers in z_pt_cor would remain.
@PennyHow, @ladsmund  any objection?
=> renaming OOL to dependent_variables + set dependencies

src/pypromice/pipeline/join_l2.py, src/pypromice/pipeline/join_l3.py, src/pypromice/pipeline/resample.py
`precip_u_cor` and `precip_l_cor` do not exist anymore
+ better resampling of `precip_u` and `precip_l`
+ bloc merging of these variables at level 2
+ removing special case for `precip_cor` in `join_l3.py`
+ no need for bloc merging of `precip` in join_l3 because it should not be outputted there
=> fixed level 2 merging of precip
